version: 2
jobs:
  build:
    docker:
      - image: cimg/node:12.22.7

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - '9f:62:d0:c6:02:f7:7d:88:30:b0:4b:a1:d0:dc:73:8e'
      - checkout
      - run:
          name: Push Main to Production
          command: |
            git push https://github.com/jjjjjjonathan/scheduler.git main:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
